package poo.cursosccm.entity;
// Generated 24/10/2018 08:39:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inscripcion generated by hbm2java
 */
public class Inscripcion  implements java.io.Serializable {


     private int idinscripcion;
     private Cursos cursos;
     private Participantes participantes;
     private int condicional;
     private Date fechahora;

    public Inscripcion() {
    }

    public Inscripcion(int idinscripcion, Cursos cursos, Participantes participantes, int condicional, Date fechahora) {
       this.idinscripcion = idinscripcion;
       this.cursos = cursos;
       this.participantes = participantes;
       this.condicional = condicional;
       this.fechahora = fechahora;
    }
    
    public Inscripcion(Cursos cursos, Participantes participantes, int condicional, Date fechahora) {
       this.cursos = cursos;
       this.participantes = participantes;
       this.condicional = condicional;
       this.fechahora = fechahora;
    }
    
    public int getIdinscripcion() {
        return this.idinscripcion;
    }
    
    public void setIdinscripcion(int idinscripcion) {
        this.idinscripcion = idinscripcion;
    }
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    public Participantes getParticipantes() {
        return this.participantes;
    }
    
    public void setParticipantes(Participantes participantes) {
        this.participantes = participantes;
    }
    public int getCondicional() {
        return this.condicional;
    }
    
    public void setCondicional(int condicional) {
        this.condicional = condicional;
    }
    public Date getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(Date fechahora) {
        this.fechahora = fechahora;
    }

    @Override
    public String toString() {
        return "Inscripcion N° "+idinscripcion
                +"\nFecha y Hora: "+getFechahora()
                +"\nCurso: "+getCursos()
                +"\nEstudiante: "+getParticipantes()
                +"\nCondicional: "+getCondicional();
    }
    
//    StringBuilder retorno = new StringBuilder().append("\n Pedido: Fecha Hora Creacion: ");
//                retorno.append(fechaHoraCreacion);
//                retorno.append(" FechaHoraEntrega: ").append(fechaHoraEntrega);
//                retorno.append("\n - N° Pedido: ").append(numero);
//                retorno.append("\n - Cliente: ").append(nombreCliente);
//                retorno.append(" - Estado: ").append(estado.getNombre());
//        
//        Iterator<DetallePedido> it = detallesPedido.iterator();
//        while(it.hasNext())
//        {
//            retorno.append("\n");
//            DetallePedido detalle = it.next();
//            retorno.append(detalle.toString());
//        }
//        return  retorno.toString();

}


