package poo.cursosccm.entity;
// Generated 24/10/2018 08:39:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Participantes generated by hbm2java
 */
public class Participantes  implements java.io.Serializable {


     private int idparticipantes;
     private String apellido;
     private String nombre;
     private String direccion;
     private String telefono;
     private String email;
     private Date fechaNac;
     private String nombreTutor;
     private Set inscripcions = new HashSet(0);

    public Participantes() {
    }

	
    public Participantes(int idparticipantes, String apellido, String nombre, String direccion, String telefono, String email, Date fechaNac) {
        this.idparticipantes = idparticipantes;
        this.apellido = apellido;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.email = email;
        this.fechaNac = fechaNac;
    }
    public Participantes(int idparticipantes, String apellido, String nombre, String direccion, String telefono, String email, Date fechaNac, String nombreTutor, Set inscripcions) {
       this.idparticipantes = idparticipantes;
       this.apellido = apellido;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.fechaNac = fechaNac;
       this.nombreTutor = nombreTutor;
       this.inscripcions = inscripcions;
    }
   
    public int getIdparticipantes() {
        return this.idparticipantes;
    }
    
    public void setIdparticipantes(int idparticipantes) {
        this.idparticipantes = idparticipantes;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getNombreTutor() {
        return this.nombreTutor;
    }
    
    public void setNombreTutor(String nombreTutor) {
        this.nombreTutor = nombreTutor;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }

    @Override
    public String toString() {
        return nombre+" "+apellido;
    }

    public boolean esmenor(){
        //este metodo no aplica en la resolucion del caso de uso planteado
        //sirve para determinar si un participante debe tener un numbre de tutor o no
        return false;
    }


}


