package poo.cursosccm.entity;
// Generated 24/10/2018 08:39:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tematicas generated by hbm2java
 */
public class Tematicas  implements java.io.Serializable {


     private Integer idtematicas;
     private String tematica;
     private Set cursoses = new HashSet(0);

    public Tematicas() {
    }

	
    public Tematicas(String tematica) {
        this.tematica = tematica;
    }
    public Tematicas(String tematica, Set cursoses) {
       this.tematica = tematica;
       this.cursoses = cursoses;
    }
   
    public Integer getIdtematicas() {
        return this.idtematicas;
    }
    
    public void setIdtematicas(Integer idtematicas) {
        this.idtematicas = idtematicas;
    }
    public String getTematica() {
        return this.tematica;
    }
    
    public void setTematica(String tematica) {
        this.tematica = tematica;
    }
    public Set getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set cursoses) {
        this.cursoses = cursoses;
    }

    @Override
    public String toString() {
        return tematica;
    }

}


